### ISSUE TITLE
IS-RSA tutorial - correcting for multiple comparisons

### ISSUE THREAD

**Issue by rtansey** [naturalistic-data-analysis/naturalistic_data_analysis#2]
Hello, thank you so much for the naturalistic imaging analysis Jupyter book, it has been extremely helpful to me. However, I think that I have either found an error or I might be understanding something incorrectly in the IS-RSA tutorial. Under the multiple comparisons section, you use a function to calculate the FDR threshold from nltools.stats. Here is the code in the Jupyter book:

```
fdr_thr = fdr(pd.Series(isrsa_nn_r).values)
print(f'FDR Threshold: {fdr_thr}')

view_img(threshold(isrsa_nn_r_brain, isrsa_nn_p_brain, thr=fdr_thr).to_nifti())
```

The input to this function is the `isrsa_nn_r` values, which, as I understand, are the _r_ correlation values, not the _p_-values.

From the nltools documentation:

```
nltools.stats.fdr(p, q=0.05)
    Determine FDR threshold given a p value array and desired false discovery rate q. Written by Tal Yarkoni

    Parameters
            p – (np.array) vector of p-values
            q – (float) false discovery rate level

    Returns
        (float) p-value threshold based on independence or positive
            dependence

    Return type
        fdr_p
```

Given that the documentation states that the input to the `fdr` function is an array of _p_-values, shouldn't `isrsa_nn_p` be the input to the function, and not `isrsa_nn_r`? Or have I misunderstood something?

Thank you!

**Comment by ljchang** [comment]
Thanks @rtansey for catching this bug!  We will fix it soon.

**Comment by esfinn** [comment]
This is now fixed. Thanks again!
